server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  application:
    name: nacos-discovery-spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #启用discoveryClient网关集成,实现服务发现
      routes:
        - id: route1
          uri: lb://service-consumer  #lb://表示负载均衡
          predicates: #判断条件
            - Path=/config/**,/index/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos